# Generated by Django 5.0.3 on 2024-03-22 17:06

import train_station.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train_station", "0004_alter_route_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_station.models.train_image_file_path
            ),
        ),
    ]
